# Generated by Django 3.0.4 on 2021-07-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versionapp',
            old_name='file_ipa',
            new_name='file',
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
