# Generated by Django 3.0.4 on 2021-07-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_versionapp_version_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionapp',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
