# Generated by Django 3.0.4 on 2021-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_versionapp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files-upload/')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
