# Generated by Django 3.0.4 on 2021-07-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionapp',
            name='note',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
