# Generated by Django 3.0.4 on 2021-07-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_versionapp_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionapp',
            name='note',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
